apiVersion: apps/v1
kind: Deployment
metadata:
  name: evolve-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: evolve
  template:
    metadata:
      labels:
        app: evolve
    spec:
      containers:
      - name: evolve
        image: umamahesh571/evolve-ecommerce:latest
        ports:
        - containerPort: 8080
